# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the event', max_length=255)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('Yearly', 'Birthday'), ('Yearly', 'Anniversary'), ('Monthly', 'Monthly Bill'), ('Onetime', 'One time event'), ('Daily', 'Daily')], max_length=255)),
                ('day', models.PositiveIntegerField(default=0, help_text='Day of the event')),
                ('month', models.PositiveIntegerField(default=0, help_text='Month of the                                       event')),
                ('year', models.PositiveIntegerField(default=0, help_text='Year of the                                        event')),
                ('hour', models.PositiveIntegerField(default=0, help_text='Hour of the                                       event')),
                ('minute', models.PositiveIntegerField(default=0, help_text='Minute of the                                         event')),
                ('frequency', models.PositiveIntegerField(default=1, help_text='Interval for                                           notifications in hours')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
