# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Yearly', 'Birthday/Anniversary'), ('Monthly', 'Monthly Bill'), ('Onetime', 'One time event'), ('Daily', 'Daily')], max_length=255),
        ),
    ]
